# Autogenerated by nbdev

d = { 'settings': {'branch': 'main', 'doc_baseurl': '/', 'doc_host': '', 'git_url': '', 'lib_path': 'nbdev_practice'},
  'syms': {'nbdev_practice.core': {'nbdev_practice.core.say_hello': ('core.html#say_hello', 'nbdev_practice/core.py')}}}
