"""My first nbdev notebook"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['say_hello']

# %% ../nbs/00_core.ipynb #ee917a06
def say_hello(name):
    """Greet someone by name"""
    return f"Hello, {name}!"
